# Bot credentials
appid: "102106051"
secret: "j1JbtCVo7Qj2LfzJdxHbwHcxIdzLh3Pm"

# Environment settings
sandbox: true  # Set to false for production

# HTTP server settings (for Webhook)
server:
  host: "0.0.0.0"
  port: 8080
  path: "/qqbot"